blank_issues_enabled: false
contact_links:
  - name: "📚 Read docs"
    url: https://docs.jina.ai/
    about: Find your solution from our documenations
  - name: "🐣 Learn examples"
    url: https://github.com/jina-ai/examples
    about: Learn from real-world examples
  - name: "😊 Join us"
    url: https://career.jina.ai
    about: Shape the neural search ecosystem in open-source!